# .github/workflows/ci-cd.yml
name: Full DevOps Pipeline

on:
  push:
    branches: [ main ]  # ou "master" selon ta branche

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Java 17 et Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Lancer les tests unitaires
      - name: Run tests
        run: mvn test

      # 4. Build l'application (génère le .jar)
      - name: Build with Maven
        run: mvn clean package -DskipTests  # skipTests car déjà lancés

